version: "3.5"

services:
  redis:
    image: redis:latest
    networks:
      - redisnet

  postgres:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    networks:
      - postgresnet

  django_asgi:
    container_name: django_asgi
    build: .
    #command: python manage.py runserver 0.0.0.0:8000
    command: daphne -b 0.0.0.0 -p 8000 --root-path=/jotlet jotlet.asgi:application
    volumes:
      - .:/code
    networks:
      - webnet
      - redisnet
      - postgresnet
    links:
      - redis
      - postgres

  nginx:
    image: nginx:stable
    depends_on:
      - django_asgi
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./nginx:/nginx
      - ./static:/static
    networks:
      - webnet
    ports:
      - "8001:443"

networks:
  webnet:
  redisnet:
  postgresnet:

volumes:
  postgres_data:
