version: "3.7"

x-environment: &default-environment
  POSTGRES_USER: vscode
  POSTGRES_PASSWORD: notsecure
  POSTGRES_DB: jotlet

services:
  redis:
    image: redis:7-alpine
    command: redis-server --maxmemory-policy volatile-lru --maxmemory 500M
    ports:
      - "6379:6379"

  postgres16:
    image: postgres:16-alpine
    volumes:
      - jotlet_postgres16_data:/var/lib/postgresql/data
    environment:
      <<: *default-environment
    ports:
      - "5432:5432"

volumes:
  jotlet_postgres16_data:
