[tool.black]
line-length = 118 # override black's default line-length

[tool.djlint]
ignore = "H006,H016,H023,T002"
format_attribute_template_tags = true
max_line_length = 118
profile = "django"

[tool.isort]
# make it compatible with black
profile = "black"
line_length = 118
