[tool.black]
line-length = 118 # override black's default line-length

[tool.coverage.run]
omit = "*/tests/*"
plugins = ["django_coverage_plugin"]

[tool.django-stubs]
django_settings_module = "jotlet.settings"

[tool.djlint]
format_css = false
format_js = false
ignore = "H016"
format_attribute_template_tags = true
max_line_length = 118
profile = "django"

[tool.djlint.css]
indent_size = 2

[tool.djlint.js]
indent_size = 2

[tool.isort]
# make it compatible with black
profile = "black"
line_length = 118

[tool.mypy]
plugins = ["mypy_django_plugin.main"]
disable_error_code = ["attr-defined"]
exclude = ["migrations"]

[tool.poetry]
name = "jotlet"
version = "1.10.6"
description = ""
authors = ["Oscar Siles Brügge <siles.oscar@gmail.com>"]
license = "GPL-3.0-or-later"

[tool.poetry.dependencies]
boto3 = "^1.26.154"
channels = "^4.0.0"
channels-redis = "^4.1.0"
crispy-bootstrap5 = "^0.7"
Django = { extras = ["argon2"], version = "^4.2.2" }
django-allauth = "^0.54.0"
django-anymail = { extras = ["mailgun", "sendgrid"], version = "^10.0" }
django-auto-prefetch = "^1.6.0"
django-axes = {extras = ["ipware"], version = "^6.0.2"}
django-cacheops = "^7.0.1"
django-cleanup = "^7.0.0"
django-cors-headers = "^4.1.0"
django-csp = "^3.7"
django-environ = "^0.10.0"
django-extra-views = "^0.14.0"
django-filter = "^23.2"
django-htmx = "^1.15.0"
django-huey-email-backend = "^0.1.1"
django-huey-monitor = "^0.6.0"
django-qr-code = "^3.1.1"
django-redis = "^5.2.0"
django-shortuuidfield = "^0.1.3"
django-simple-history = "^3.3.0"
django-storages = "^1.13.2"
django-tree-queries = "^0.14.0"
gunicorn = "^20.1.0"
httpx = "^0.24.1"
huey = "^2.4.5"
Pillow = "^9.5.0"
psycopg = { extras = ["binary"], version = "^3.1.9" }
python = ">=3.10,<4.0.0"
redis = { extras = ["hiredis"], version = "^4.5.5" }
sentry-sdk = "^1.25.1"
sorl-thumbnail = "^12.9.0"
uvicorn = { extras = ["standard"], version = "^0.22.0" }
whitenoise = "^6.4.0"

[tool.poetry.group.dev.dependencies]
autoflake8 = "^0.4.0"
black = "^23.3.0"
coverage = { extras = ["toml"], version = "^7.2.7" }
django-coverage-plugin = "^3.0.0"
django-debug-toolbar = "^4.1.0"
django-debug-toolbar-template-profiler = "^2.1.0"
django-stubs = { extras = ["compatible-mypy"], version = "^4.2.1" }
djlint = "^1.31.0"
flake8 = "^6.0.0"
isort = "^5.12.0"
pylint-django = "^2.5.3"
pytest-cov = "^4.1.0"
pyupgrade = "^3.6.0"

[tool.poetry.group.test.dependencies]
daphne = "^4.0.0"
factory-boy = "^3.2.1"
pytest = "^7.3.2"
pytest-asyncio = "^0.21.0"
pytest-django = "^4.5.2"
pytest-factoryboy = "^2.5.1"
pytest-lazy-fixture = "^0.6.3"
pytest-randomly = "^3.12.0"
pytest-xdist = "^3.3.1"

[tool.pylint]
disable = "no-member"
django-settings-module = "jotlet.settings"
ignored-argument-names = "arg|args|kwargs|sender"
ignore-paths = ".*/migrations"
load-plugins = "pylint_django"
max-line-length = 118

[tool.pytest.ini_options]
addopts = "--cov=jotlet --cov-report xml:cov.xml --cov-report html:htmlcov"

[build-system]
requires = ["poetry-core>=1.1.0"]
build-backend = "poetry.core.masonry.api"
