[tool.black]
line-length = 118 # override black's default line-length

[tool.coverage.run]
plugins = ["django_coverage_plugin"]

[tool.django-stubs]
django_settings_module = "jotlet.settings"

[tool.djlint]
format_css = false
format_js = false
ignore = "H016"
format_attribute_template_tags = true
max_line_length = 118
profile = "django"

[tool.djlint.css]
indent_size = 2

[tool.djlint.js]
indent_size = 2

[tool.isort]
# make it compatible with black
profile = "black"
line_length = 118

[tool.mypy]
plugins = ["mypy_django_plugin.main"]

[tool.pylint]
max-line-length = 118

[tool.poetry]
name = "jotlet"
version = "1.7.4"
description = ""
authors = ["Oscar Siles Brügge <siles.oscar@gmail.com>"]
license = "GPL-3.0-or-later"

[tool.poetry.dependencies]
boto3 = "^1.26.80"
channels = "^4.0.0"
channels-redis = "^4.0.0"
crispy-bootstrap5 = "^0.7"
Django = { extras = ["argon2"], version = "^4.1.7" }
django = { extras = ["argon2"], version = "^4.1.7" }
django-allauth = "^0.52.0"
django-anymail = { extras = ["mailgun", "sendgrid"], version = "^9.0" }
django-auto-prefetch = "^1.4.0"
django-axes = "^5.40.1"
django-cachalot = "^2.5.2"
django-cacheops = "^6.2"
django-cleanup = "^7.0.0"
django-cors-headers = "^3.13.0"
django-csp = "^3.7"
django-environ = "^0.9.0"
django-filter = "^22.1"
django-htmx = "^1.13.0"
django-huey-email-backend = "^0.1.1"
django-huey-monitor = "^0.6.0"
django-qr-code = "^3.1.1"
django-redis = "^5.2.0"
django-shortuuidfield = "^0.1.3"
django-simple-history = "^3.2.0"
django-storages = "^1.13.2"
django-tree-queries = "^0.14.0"
gunicorn = "^20.1.0"
httpx = "^0.23.3"
huey = "^2.4.5"
Pillow = "^9.4.0"
psycopg2 = "^2.9.5"
python = "^3.8.1"
redis = { extras = ["hiredis"], version = "^4.5.1" }
sentry-sdk = "^1.15.0"
sorl-thumbnail = "^12.9.0"
uvicorn = { extras = ["standard"], version = "^0.20.0" }
whitenoise = "^6.3.0"

[tool.poetry.group.dev.dependencies]
autoflake8 = "^0.4.0"
black = "^23.1.0"
coverage = { extras = ["toml"], version = "^7.2.0" }
django-coverage-plugin = "^3.0.0"
django-debug-toolbar = "^3.8.1"
django-debug-toolbar-template-profiler = "^2.1.0"
django-stubs = "^1.15.0"
djlint = "^1.19.15"
flake8 = "^6.0.0"
isort = "^5.12.0"
mypy = "^1.0.1"
pylint-django = "^2.5.3"
pytest-cov = "^4.0.0"
pyupgrade = "^3.3.1"

[tool.poetry.group.test.dependencies]
daphne = "^4.0.0"
factory-boy = "^3.2.1"
pytest = "^7.2.1"
pytest-asyncio = "^0.20.3"
pytest-django = "^4.5.2"
pytest-factoryboy = "^2.5.1"
pytest-lazy-fixture = "^0.6.3"
pytest-randomly = "^3.12.0"
pytest-xdist = "^3.2.0"

[build-system]
requires = ["poetry-core>=1.1.0"]
build-backend = "poetry.core.masonry.api"
