[tool.black]
line-length = 118 # override black's default line-length

[tool.djlint]
format_css = false
format_js = false
ignore = "H016"
format_attribute_template_tags = true
max_line_length = 118
profile = "django"

[tool.djlint.css]
indent_size = 2

[tool.djlint.js]
indent_size = 2

[tool.isort]
# make it compatible with black
profile = "black"
line_length = 118

[tool.poetry]
name = "jotlet"
version = "1.3.9"
description = ""
authors = ["Oscar Siles Brügge <siles.oscar@gmail.com>"]
license = "GPL-3.0-or-later"

[tool.poetry.dependencies]
boto3 = "^1.24.81"
channels = "^3.0.5"
channels-redis = "^3.4.1"
crispy-bootstrap5 = "^0.6"
Django = { extras = ["argon2"], version = "^4.1.1" }
django-allauth = "^0.51.0"
django-anymail = { extras = ["mailgun", "sendgrid"], version = "^8.6" }
django-auto-prefetch = "^1.3.0"
django-axes = "^5.39.0"
django-cachalot = "^2.5.2"
django-cacheops = "^6.1"
django-cleanup = "^6.0.0"
django-cors-headers = "^3.13.0"
django-csp = "^3.7"
django-environ = "^0.9.0"
django-filter = "^22.1"
django-htmx = "^1.12.2"
django-huey-email-backend = "^0.1.1"
django-huey-monitor = "^0.5.0"
django-mptt = "^0.13.4"
django-qr-code = "^3.1.1"
django-redis = "^5.2.0"
django-shortuuidfield = "^0.1.3"
django-simple-history = "^3.1.1"
django-storages = "^1.13.1"
gunicorn = "^20.1.0"
httpx = "^0.23.0"
huey = "^2.4.3"
Pillow = "^9.2.0"
psycopg2 = "^2.9.3"
python = "^3.8"
redis = { extras = ["hiredis"], version = "^4.3.4" }
sentry-sdk = "^1.9.9"
sorl-thumbnail = "^12.9.0"
uvicorn = { extras = ["standard"], version = "^0.18.3" }
whitenoise = "^6.2.0"

[tool.poetry.group.dev.dependencies]
autoflake8 = "^0.3.2"
black = "^22.8.0"
django-debug-toolbar = "^3.7.0"
django-debug-toolbar-template-profiler = "^2.1.0"
djlint = "^1.18.0"
flake8 = "^5.0.4"
isort = "^5.10.1"
poetryup = "^0.10.0"
pyupgrade = "^2.38.2"

[tool.poetry.group.test.dependencies]
coverage = "^6.4.4"
daphne = "^3.0.2"
factory-boy = "^3.2.1"
pytest-cov = "^3.0.0"
pytest-django = "^4.5.2"

[build-system]
requires = ["poetry-core>=1.1.0"]
build-backend = "poetry.core.masonry.api"
