[tool.black]
line-length = 118 # override black's default line-length

[tool.djlint]
format_css = true
format_js = true
ignore = "H006,H016,H023,T002"
format_attribute_template_tags = true
max_line_length = 118
profile = "django"

[tool.djlint.css]
indent_size = 2

[tool.djlint.js]
indent_size = 2

[tool.isort]
# make it compatible with black
profile = "black"
line_length = 118

[tool.poetry]
name = "jotlet"
version = "0.1.0"
description = ""
authors = []
license = "GPL-3.0"

[tool.poetry.dependencies]
python = "^3.8"
boto3 = "^1.24.56"
channels-redis = { extras = ["cryptography"], version = "^3.4.1" }
channels = "^3.0.5"
crispy-bootstrap5 = "^0.6"
django-allauth = "^0.51.0"
django-anymail = { extras = ["mailgun", "sendgrid"], version = "^8.6" }
django-auto-prefetch = "^1.3.0"
django-axes = "^5.39.0"
django-cachalot = "^2.5.1"
django-cacheops = "^6.1"
django-cleanup = "^6.0.0"
django-cors-headers = "^3.13.0"
django-csp = "^3.7"
django-environ = "^0.9.0"
django-filter = "^22.1"
django-htmx = "^1.12.1"
django-jazzmin = "^2.5.0"
django-mptt = "^0.13.4"
django-q = "^1.3.9"
django-q-email = "^5.0.1"
django-qr-code = "^3.1.1"
django-redis = "^5.2.0"
django-shortuuidfield = "^0.1.3"
django-simple-history = "^3.1.1"
django-storages = "^1.13.1"
Django = { extras = ["argon2"], version = "^4.0.7" }
gunicorn = "^20.1.0"
hiredis = "^2.0.0"
httpx = "^0.23.0"
Pillow = "^9.2.0"
psycopg2 = "^2.9.3"
sentry-sdk = "^1.9.5"
sorl-thumbnail = "^12.8.0"
uvicorn = { extras = ["standard"], version = "^0.18.2" }
whitenoise = { extras = ["brotli"], version = "^6.2.0" }

[tool.poetry.dev-dependencies]
autoflake8 = "^0.3.2"
black = "^22.6.0"
coverage = "^6.4.4"
django-debug-toolbar = "^3.6.0"
django-debug-toolbar-template-profiler = "^2.1.0"
djlint = "^1.11.1"
flake8 = "^5.0.4"
isort = "^5.10.1"
locust = "^2.11.0"
poetryup = "^0.10.0"
pytest-django = "^4.5.2"
pyupgrade = "^2.37.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
