# Generated by Django 4.0.4 on 2022-04-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaluserprofile',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Profile'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterField(
            model_name='historicaluserprofile',
            name='optin_newsletter',
            field=models.BooleanField(default=False, verbose_name='Opt-in to newsletter'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='optin_newsletter',
            field=models.BooleanField(default=False, verbose_name='Opt-in to newsletter'),
        ),
    ]
