# Generated by Django 4.0.4 on 2022-05-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_historicaluserprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaluserprofile',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Profile', 'verbose_name_plural': 'historical Profiles'},
        ),
        migrations.AlterField(
            model_name='historicaluserprofile',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
