# Generated by Django 4.0.7 on 2022-08-23 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_managers_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaluserprofile',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical profile', 'verbose_name_plural': 'historical profiles'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'profile'},
        ),
    ]
