# Generated by Django 4.1.3 on 2022-11-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_user_options_alter_user_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluserprofile",
            name="boards_paginate_by",
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="boards_paginate_by",
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
