# Generated by Django 4.1.3 on 2022-11-09 10:16

from django.db import migrations, models


def migrate_optin_newsletter(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    for user in User.objects.all():
        user.profile.optin_newsletter = user.optin_newsletter
        user.profile.save(update_fields=["optin_newsletter"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_historicaluserprofile_boards_paginate_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluserprofile",
            name="optin_newsletter",
            field=models.BooleanField(default=False, verbose_name="Opt-in to newsletter"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="optin_newsletter",
            field=models.BooleanField(default=False, verbose_name="Opt-in to newsletter"),
        ),
        migrations.RunPython(migrate_optin_newsletter, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="user",
            name="optin_newsletter",
        ),
    ]
