# Generated by Django 4.1.3 on 2022-11-14 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_remove_user_optin_newsletter_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={"base_manager_name": "prefetch_manager", "verbose_name": "profile"},
        ),
    ]
