# Generated by Django 4.2.1 on 2023-05-09 21:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_remove_historicaluserprofile_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaluserprofile",
            name="history_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
