# Generated by Django 4.2.1 on 2023-05-09 21:57

import uuid

from django.db import migrations, models


def gen_uuid(apps, schema_editor):
    Model = apps.get_model("accounts", "userprofile")
    for row in Model.objects.all():
        while True:
            row.uuid = uuid.uuid4()
            if not Model.objects.filter(uuid=row.uuid).exists():
                break
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_alter_historicaluserprofile_history_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
