# Generated by Django 4.2.1 on 2023-05-09 21:59

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_user_uuid_userprofile_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
