# Generated by Django 4.2.1 on 2023-05-10 18:30

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0017_historicaluserprofile"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="userprofile",
            index=django.contrib.postgres.indexes.BrinIndex(
                autosummarize=True, fields=["created_at"], name="accounts_us_created_c69f42_brin"
            ),
        ),
    ]
