# Generated by Django 5.0 on 2023-12-05 15:35

import django.contrib.postgres.functions
import uuid
from django.db import migrations, models

def gen_uuid(apps, schema_editor):
    Model = apps.get_model("accounts", "user")
    for row in Model.objects.all():
        while Model.objects.filter(uuid=row.uuid).count() > 1:
            row.uuid = uuid.uuid4()
            row.save(update_fields=["uuid"])

class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0020_alter_userprofile_boards_paginate_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(
                db_default=django.contrib.postgres.functions.RandomUUID(),
                default=uuid.uuid4,
                editable=False,
            ),
        ),
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(
                db_default=django.contrib.postgres.functions.RandomUUID(),
                default=uuid.uuid4,
                editable=False,
                unique=True,
            ),
        ),
    ]
