# Generated by Django 5.0.2 on 2024-02-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0021_user_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="boards_paginate_by",
            field=models.PositiveSmallIntegerField(db_default=10),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="optin_newsletter",
            field=models.BooleanField(
                db_default=False, verbose_name="Opt-in to newsletter"
            ),
        ),
    ]
