# Generated by Django 4.0.2 on 2022-02-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_board_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='session_key',
            field=models.CharField(default='', max_length=40),
        ),
    ]
