# Generated by Django 4.0.2 on 2022-02-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_post_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
