# Generated by Django 4.0.2 on 2022-02-02 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_alter_board_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('can_delete_post', 'Can delete post'),)},
        ),
    ]
