# Generated by Django 4.0.2 on 2022-02-02 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0011_alter_board_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('can_delete_post', 'Can delete post'), ('can_edit_post', 'Can edit post'))},
        ),
    ]
