# Generated by Django 4.0.2 on 2022-02-02 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0012_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
