# Generated by Django 4.0.2 on 2022-02-08 20:39

import boards.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0013_alter_post_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('attribution', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(upload_to=boards.models.get_image_upload_path)),
                ('type', models.CharField(choices=[('b', 'Background')], default='b', help_text='Image type', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='BoardPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='background', to='boards.image')),
                ('board', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='boards.board')),
            ],
        ),
    ]
