# Generated by Django 4.0.2 on 2022-02-09 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0014_image_boardpreferences'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='photo',
            new_name='image',
        ),
    ]
