# Generated by Django 4.0.2 on 2022-02-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0018_alter_boardpreferences_background_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='post',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
