# Generated by Django 4.0.2 on 2022-02-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0019_alter_image_options_post_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
