# Generated by Django 4.0.2 on 2022-02-14 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0020_alter_post_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('can_approve_post', 'Can approve posts'),)},
        ),
    ]
