# Generated by Django 4.0.2 on 2022-02-14 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0021_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('can_approve_posts', 'Can approve posts'),)},
        ),
    ]
