# Generated by Django 4.0.2 on 2022-03-01 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0022_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='type',
            field=models.CharField(choices=[('b', 'Background'), ('p', 'Post')], default='b', help_text='Image type', max_length=1),
        ),
    ]
