# Generated by Django 4.0.3 on 2022-03-01 14:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0023_alter_image_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardpreferences',
            name='moderators',
            field=models.ManyToManyField(blank=True, related_name='moderated_boards', to=settings.AUTH_USER_MODEL),
        ),
    ]
