# Generated by Django 4.0.3 on 2022-04-05 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0024_boardpreferences_moderators'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardpreferences',
            name='reaction_type',
            field=models.CharField(choices=[('n', 'None'), ('l', 'Like'), ('v', 'Vote'), ('s', 'Star')], default='n', max_length=1),
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('type', models.CharField(choices=[('n', 'None'), ('l', 'Like'), ('v', 'Vote'), ('s', 'Star')], default='l', max_length=1)),
                ('reaction_score', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='boards.post')),
            ],
            options={
                'unique_together': {('post', 'session_key', 'type')},
            },
        ),
    ]
