# Generated by Django 4.0.4 on 2022-04-14 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0029_historicaltopic_historicalpost_historicalimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalBoardPreferences',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('background_type', models.CharField(choices=[('c', 'Color'), ('i', 'Image')], default='c', max_length=1)),
                ('background_color', models.CharField(default='#ffffff', max_length=7)),
                ('background_opacity', models.FloatField(default=1.0)),
                ('enable_latex', models.BooleanField(default=False)),
                ('require_approval', models.BooleanField(default=False)),
                ('reaction_type', models.CharField(choices=[('n', 'None'), ('l', 'Like'), ('v', 'Vote'), ('s', 'Star')], default='n', max_length=1)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('background_image', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='boards.image')),
                ('board', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='boards.board')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical board preferences',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
