# Generated by Django 4.0.4 on 2022-04-19 12:05

from django.contrib.postgres.operations import BtreeGinExtension, TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0030_historicalboardpreferences"),
    ]

    operations = [
        TrigramExtension(),
        BtreeGinExtension(),
    ]
