# Generated by Django 4.0.4 on 2022-04-19 12:26

import django.contrib.postgres.indexes
from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0031_add_postgres_extensions'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='board',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('title'), name='gin_trgm_ops'), name='upper_title_idx'),
        ),
        migrations.AddIndex(
            model_name='board',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('description'), name='gin_trgm_ops'), name='upper_description_idx'),
        ),
        migrations.AddIndex(
            model_name='board',
            index=django.contrib.postgres.indexes.BrinIndex(autosummarize=True, fields=['created_at'], name='boards_boar_created_eb1e77_brin'),
        ),
    ]
