# Generated by Django 4.0.4 on 2022-04-27 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0033_userprofile_historicaluserprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='HistoricalUserProfile',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
