# Generated by Django 4.0.4 on 2022-05-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0034_remove_userprofile_user_delete_historicaluserprofile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalboard',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical board', 'verbose_name_plural': 'historical boards'},
        ),
        migrations.AlterModelOptions(
            name='historicalboardpreferences',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical board preferences', 'verbose_name_plural': 'historical board preferencess'},
        ),
        migrations.AlterModelOptions(
            name='historicalimage',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical image', 'verbose_name_plural': 'historical images'},
        ),
        migrations.AlterModelOptions(
            name='historicalpost',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical post', 'verbose_name_plural': 'historical posts'},
        ),
        migrations.AlterModelOptions(
            name='historicaltopic',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical topic', 'verbose_name_plural': 'historical topics'},
        ),
        migrations.AlterField(
            model_name='historicalboard',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalboardpreferences',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalimage',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalpost',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaltopic',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
