# Generated by Django 4.0.5 on 2022-06-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0035_alter_historicalboard_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltopic',
            name='subject',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='topic',
            name='subject',
            field=models.CharField(max_length=400),
        ),
    ]
