# Generated by Django 4.0.5 on 2022-06-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0036_alter_historicaltopic_subject_alter_topic_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltopic',
            name='subject',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='topic',
            name='subject',
            field=models.TextField(max_length=400),
        ),
    ]
