# Generated by Django 4.0.6 on 2022-07-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0037_alter_historicaltopic_subject_alter_topic_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='historicalboard',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='board',
            name='slug',
            field=models.SlugField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalboard',
            name='slug',
            field=models.SlugField(max_length=8),
        ),
    ]
