# Generated by Django 4.0.6 on 2022-07-22 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0039_alter_historicalpost_content_alter_post_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardpreferences',
            old_name='require_approval',
            new_name='require_post_approval',
        ),
        migrations.RenameField(
            model_name='historicalboardpreferences',
            old_name='require_approval',
            new_name='require_post_approval',
        ),
        migrations.AddField(
            model_name='boardpreferences',
            name='allow_guest_replies',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boardpreferences',
            name='type',
            field=models.CharField(choices=[('d', 'Default'), ('r', 'With Replies')], default='d', max_length=1),
        ),
        migrations.AddField(
            model_name='historicalboardpreferences',
            name='allow_guest_replies',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalboardpreferences',
            name='type',
            field=models.CharField(choices=[('d', 'Default'), ('r', 'With Replies')], default='d', max_length=1),
        ),
        migrations.AddField(
            model_name='historicalpost',
            name='allow_replies',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalpost',
            name='reply_to',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='boards.post'),
        ),
        migrations.AddField(
            model_name='post',
            name='allow_replies',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='boards.post'),
        ),
    ]
