# Generated by Django 4.0.6 on 2022-07-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0040_rename_require_approval_boardpreferences_require_post_approval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpost',
            name='reply_depth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='reply_depth',
            field=models.IntegerField(default=0),
        ),
    ]
