# Generated by Django 4.0.6 on 2022-07-26 16:42

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0041_historicalpost_reply_depth_post_reply_depth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpost',
            name='reply_depth',
        ),
        migrations.AddField(
            model_name='post',
            name='lft',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='rght',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalpost',
            name='reply_to',
            field=mptt.fields.TreeForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='boards.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='reply_depth',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='reply_to',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='boards.post'),
        ),
    ]
