# Generated by Django 4.0.6 on 2022-07-26 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0041_historicalpost_reply_depth_post_reply_depth"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalpost",
            name="reply_depth",
        ),
        migrations.AddField(
            model_name="post",
            name="lft",
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="rght",
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="tree_id",
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="reply_depth",
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
