# Generated by Django 4.0.7 on 2022-08-12 12:14

import auto_prefetch
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0044_alter_boardpreferences_options_alter_topic_options_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='image',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='boardpreferences',
            name='allow_image_uploads',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalboardpreferences',
            name='allow_image_uploads',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalimage',
            name='board',
            field=auto_prefetch.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='boards.board'),
        ),
        migrations.AddField(
            model_name='image',
            name='board',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='boards.board'),
        ),
    ]
