# Generated by Django 4.0.7 on 2022-08-15 10:44

import auto_prefetch
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0045_alter_image_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalimage',
            name='post',
            field=auto_prefetch.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='boards.post'),
        ),
        migrations.AddField(
            model_name='image',
            name='post',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='boards.post'),
        ),
    ]
