# Generated by Django 4.0.7 on 2022-08-16 13:32

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0046_historicalimage_post_image_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='BgImage',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Images: Background',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('boards.image',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Images: Posts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('boards.image',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
