# Generated by Django 4.0.7 on 2022-08-16 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0047_bgimage_postimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bgimage',
            options={'verbose_name': 'background image'},
        ),
        migrations.AlterModelOptions(
            name='postimage',
            options={'verbose_name': 'post image'},
        ),
    ]
