# Generated by Django 4.1.1 on 2022-09-07 15:14

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0048_alter_bgimage_options_alter_postimage_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="historicalboard",
            name="uuid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="boardpreferences",
            name="enable_identicons",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="historicalboardpreferences",
            name="enable_identicons",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="historicalpost",
            name="identity_hash",
            field=models.CharField(max_length=64, null=True, blank=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="identity_hash",
            field=models.CharField(max_length=64, null=True, blank=True),
            preserve_default=False,
        ),
    ]
