# Generated by Django 4.1.1 on 2022-09-07 15:15

import uuid
from hashlib import blake2b

from django.db import migrations
from mptt import managers, register


def gen_uuid(apps, schema_editor):
    Board = apps.get_model("boards", "Board")
    for row in Board.objects.all():
        while True:
            row.uuid = uuid.uuid4()
            if not Board.objects.filter(uuid=row.uuid).exists():
                break
        row.save(update_fields=["uuid"])


def gen_hash(apps, schema_editor):
    # from django-mptt github issues
    Post = apps.get_model("boards", "Post")
    manager = managers.TreeManager()
    manager.model = Post
    register(Post, parent_attr="reply_to", level_attr="reply_depth")
    manager.contribute_to_class(Post, "objects")
    manager.rebuild()
    for row in Post.objects.all():
        string = row.user.username if row.user is not None else row.session_key
        salt = row.topic.board.uuid
        row.identity_hash = blake2b(f"{string}{salt}".encode(), digest_size=32).hexdigest()
        row.save(update_fields=["identity_hash"])


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0049_board_uuid_historicalboard_uuid_and_more"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(gen_hash, reverse_code=migrations.RunPython.noop),
    ]
