# Generated by Django 4.1.1 on 2022-09-07 15:15

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0050_populate_uuid_and_identity_hash_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
