# Generated by Django 4.1.1 on 2022-09-12 21:31

import auto_prefetch
from django.conf import settings
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("boards", "0051_remove_uuid_and_identity_hash_null"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="owner",
            field=auto_prefetch.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
