# Generated by Django 4.1.1 on 2022-09-27 07:48

import auto_prefetch
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0053_boardpreferences_posting_available_from_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boardpreferences",
            name="background_image",
            field=auto_prefetch.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="background",
                to="boards.bgimage",
            ),
        ),
        migrations.AlterField(
            model_name="historicalboardpreferences",
            name="background_image",
            field=auto_prefetch.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="boards.bgimage",
            ),
        ),
    ]
