# Generated by Django 4.1.2 on 2022-10-04 13:45

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0054_alter_boardpreferences_background_image_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="post",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name="historicalpost",
            name="lft",
        ),
        migrations.RemoveField(
            model_name="historicalpost",
            name="reply_depth",
        ),
        migrations.RemoveField(
            model_name="historicalpost",
            name="reply_to",
        ),
        migrations.RemoveField(
            model_name="historicalpost",
            name="rght",
        ),
        migrations.RemoveField(
            model_name="historicalpost",
            name="tree_id",
        ),
        migrations.RemoveField(
            model_name="post",
            name="lft",
        ),
        migrations.RemoveField(
            model_name="post",
            name="reply_depth",
        ),
        migrations.RemoveField(
            model_name="post",
            name="reply_to",
        ),
        migrations.RemoveField(
            model_name="post",
            name="rght",
        ),
        migrations.RemoveField(
            model_name="post",
            name="tree_id",
        ),
        migrations.AddField(
            model_name="historicalpost",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="boards.post",
                verbose_name="parent",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="boards.post",
                verbose_name="parent",
            ),
        ),
    ]
