# Generated by Django 4.1.2 on 2022-10-06 11:13

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0055_alter_post_managers_remove_historicalpost_lft_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="boardpreferences",
            options={},
        ),
        migrations.AlterModelOptions(
            name="topic",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="reaction",
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name="boardpreferences",
            index=django.contrib.postgres.indexes.BrinIndex(
                autosummarize=True, fields=["posting_allowed_from"], name="boards_boar_posting_c1cd94_brin"
            ),
        ),
        migrations.AddIndex(
            model_name="boardpreferences",
            index=django.contrib.postgres.indexes.BrinIndex(
                autosummarize=True, fields=["posting_allowed_until"], name="boards_boar_posting_986f73_brin"
            ),
        ),
        migrations.AddIndex(
            model_name="image",
            index=django.contrib.postgres.indexes.BrinIndex(
                autosummarize=True, fields=["created_at"], name="boards_imag_created_8b4aa3_brin"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=django.contrib.postgres.indexes.BrinIndex(
                autosummarize=True, fields=["created_at"], name="boards_post_created_dd163c_brin"
            ),
        ),
        migrations.AddIndex(
            model_name="reaction",
            index=django.contrib.postgres.indexes.BrinIndex(
                autosummarize=True, fields=["created_at"], name="boards_reac_created_189025_brin"
            ),
        ),
        migrations.AddIndex(
            model_name="topic",
            index=django.contrib.postgres.indexes.BrinIndex(
                autosummarize=True, fields=["created_at"], name="boards_topi_created_1fa27e_brin"
            ),
        ),
        migrations.AddConstraint(
            model_name="reaction",
            constraint=models.UniqueConstraint(
                fields=("post", "session_key", "type"), name="unique_anonymous_reaction"
            ),
        ),
        migrations.AddConstraint(
            model_name="reaction",
            constraint=models.UniqueConstraint(fields=("post", "user", "type"), name="unique_user_reaction"),
        ),
    ]
