# Generated by Django 4.1.3 on 2022-11-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0056_alter_boardpreferences_options_alter_topic_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="description",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="historicalboard",
            name="description",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
