# Generated by Django 4.1.3 on 2022-11-14 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0057_alter_board_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bgimage",
            options={"base_manager_name": "prefetch_manager", "verbose_name": "background image"},
        ),
        migrations.AlterModelOptions(
            name="board",
            options={
                "base_manager_name": "prefetch_manager",
                "permissions": (("can_view_all_boards", "Can view all boards"),),
            },
        ),
        migrations.AlterModelOptions(
            name="boardpreferences",
            options={"base_manager_name": "prefetch_manager"},
        ),
        migrations.AlterModelOptions(
            name="image",
            options={"base_manager_name": "prefetch_manager", "ordering": ["title"]},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={
                "base_manager_name": "prefetch_manager",
                "permissions": (("can_approve_posts", "Can approve posts"),),
            },
        ),
        migrations.AlterModelOptions(
            name="postimage",
            options={"base_manager_name": "prefetch_manager", "verbose_name": "post image"},
        ),
        migrations.AlterModelOptions(
            name="reaction",
            options={"base_manager_name": "prefetch_manager"},
        ),
        migrations.AlterModelOptions(
            name="topic",
            options={"base_manager_name": "prefetch_manager"},
        ),
    ]
