# Generated by Django 4.1.7 on 2023-03-30 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boards", "0058_alter_bgimage_options_alter_board_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="board",
            options={
                "base_manager_name": "prefetch_manager",
                "permissions": (
                    ("can_view_all_boards", "Can view all boards"),
                    ("lock_board", "Can (un)lock all boards"),
                ),
            },
        ),
        migrations.AddField(
            model_name="board",
            name="locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="boardpreferences",
            name="allow_post_editing",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="boardpreferences",
            name="require_post_reapproval_on_edit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalboard",
            name="locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalboardpreferences",
            name="allow_post_editing",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="historicalboardpreferences",
            name="require_post_reapproval_on_edit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicaltopic",
            name="locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="topic",
            name="locked",
            field=models.BooleanField(default=False),
        ),
    ]
