# Generated by Django 4.2 on 2023-04-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boards", "0059_alter_board_options_board_locked_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="boardpreferences",
            name="enable_chemdoodle",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalboardpreferences",
            name="enable_chemdoodle",
            field=models.BooleanField(default=False),
        ),
    ]
