# Generated by Django 4.2.1 on 2023-05-09 15:26

import uuid

import auto_prefetch
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models

import jotlet.mixins.refresh_from_db_invalidates_cached_properties


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("boards", "0060_boardpreferences_enable_chemdoodle_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalboard",
            name="locked",
        ),
        migrations.RemoveField(
            model_name="historicalboard",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="historicalboardpreferences",
            name="board",
        ),
        migrations.RemoveField(
            model_name="historicalimage",
            name="board",
        ),
        migrations.RemoveField(
            model_name="historicalimage",
            name="image",
        ),
        migrations.RemoveField(
            model_name="historicalimage",
            name="post",
        ),
        migrations.RemoveField(
            model_name="historicalimage",
            name="type",
        ),
        migrations.RemoveField(
            model_name="historicalpost",
            name="allow_replies",
        ),
        migrations.RemoveField(
            model_name="historicalpost",
            name="approved",
        ),
        migrations.RemoveField(
            model_name="historicalpost",
            name="identity_hash",
        ),
        migrations.RemoveField(
            model_name="historicalpost",
            name="topic",
        ),
        migrations.RemoveField(
            model_name="historicaltopic",
            name="board",
        ),
        migrations.RemoveField(
            model_name="historicaltopic",
            name="locked",
        ),
        migrations.CreateModel(
            name="HistoricalAdditionalData",
            fields=[
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("json", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical additional data",
                "verbose_name_plural": "historical additional datas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
        ),
        migrations.CreateModel(
            name="AdditionalData",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[("m", "misc"), ("c", "chemdoodle")], default="m", editable=False, max_length=1
                    ),
                ),
                ("json", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "post",
                    auto_prefetch.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="additional_data", to="boards.post"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            bases=(
                jotlet.mixins.refresh_from_db_invalidates_cached_properties.InvalidateCachedPropertiesMixin,
                models.Model,
            ),
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name="additionaldata",
            constraint=models.UniqueConstraint(fields=("post", "type"), name="unique_post_additional_data_type"),
        ),
    ]
