# Generated by Django 4.2.1 on 2023-05-09 21:22

import uuid

from django.db import migrations, models


def gen_uuid(apps, schema_editor):
    tables = [
        "historicaladditionaldata",
        "historicalboard",
        "historicalboardpreferences",
        "historicalimage",
        "historicalpost",
        "historicaltopic",
    ]
    for table in tables:
        Model = apps.get_model("boards", table)
        for row in Model.objects.all():
            old_id = row.history_id
            while True:
                row.history_id = uuid.uuid4()
                if not Model.objects.filter(history_id=row.history_id).exists():
                    break
            row.save()
            Model.objects.get(history_id=old_id).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("boards", "0061_remove_historicalboard_locked_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaladditionaldata",
            name="history_id",
            field=models.CharField(
                auto_created=True, editable=False, max_length=36, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="historicalboard",
            name="history_id",
            field=models.CharField(
                auto_created=True, editable=False, max_length=36, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="historicalboardpreferences",
            name="history_id",
            field=models.CharField(
                auto_created=True, editable=False, max_length=36, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="historicalimage",
            name="history_id",
            field=models.CharField(
                auto_created=True, editable=False, max_length=36, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="historicalpost",
            name="history_id",
            field=models.CharField(
                auto_created=True, editable=False, max_length=36, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="historicaltopic",
            name="history_id",
            field=models.CharField(
                auto_created=True, editable=False, max_length=36, primary_key=True, serialize=False
            ),
        ),
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
