# Generated by Django 4.2.1 on 2023-05-09 21:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("boards", "0062_alter_historicaladditionaldata_history_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaladditionaldata",
            name="history_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="historicalboard",
            name="history_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="historicalboardpreferences",
            name="history_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="historicalimage",
            name="history_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="historicalpost",
            name="history_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="historicaltopic",
            name="history_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
