# Generated by Django 4.2.1 on 2023-05-09 22:13
import auto_prefetch
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("boards", "0066_remove_board_id_remove_boardpreferences_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="additionaldata",
            old_name="uuid",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="board",
            old_name="uuid",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="boardpreferences",
            old_name="uuid",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="image",
            old_name="uuid",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="uuid",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="reaction",
            old_name="uuid",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="topic",
            old_name="uuid",
            new_name="id",
        ),
        migrations.AlterField(
            model_name="boardpreferences",
            name="board",
            field=auto_prefetch.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="preferences", to="boards.board"
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="board",
            field=auto_prefetch.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="topics", to="boards.board"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="topic",
            field=auto_prefetch.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="posts", to="boards.topic"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="boards.post",
                verbose_name="parent",
            ),
        ),
        migrations.AlterField(
            model_name="additionaldata",
            name="post",
            field=auto_prefetch.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="additional_data", to="boards.post"
            ),
        ),
        migrations.AlterField(
            model_name="reaction",
            name="post",
            field=auto_prefetch.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="reactions", to="boards.post"
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="post",
            field=auto_prefetch.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="boards.post",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="board",
            field=auto_prefetch.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="boards.board",
            ),
        ),
        migrations.AddField(
            model_name="boardpreferences",
            name="moderators",
            field=models.ManyToManyField(blank=True, related_name="moderated_boards", to=settings.AUTH_USER_MODEL),
        ),
    ]
