# Generated by Django 4.2.1 on 2023-05-10 09:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("boards", "0067_rename_uuid_additionaldata_id_rename_uuid_board_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="additionaldata",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="board",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="boardpreferences",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="image",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="reaction",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="topic",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name="additionaldata",
            constraint=models.UniqueConstraint(fields=("post", "type"), name="unique_post_additional_data_type"),
        ),
        migrations.AddConstraint(
            model_name="reaction",
            constraint=models.UniqueConstraint(
                fields=("post", "session_key", "type"), name="unique_anonymous_reaction"
            ),
        ),
        migrations.AddConstraint(
            model_name="reaction",
            constraint=models.UniqueConstraint(fields=("post", "user", "type"), name="unique_user_reaction"),
        ),
    ]
