# Generated by Django 4.2.1 on 2023-05-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boards", "0070_boardpreferences_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="board",
            options={
                "base_manager_name": "prefetch_manager",
                "ordering": ["created_at"],
                "permissions": (
                    ("can_view_all_boards", "Can view all boards"),
                    ("lock_board", "Can (un)lock all boards"),
                ),
            },
        ),
        migrations.AlterModelOptions(
            name="image",
            options={"base_manager_name": "prefetch_manager", "ordering": ["title", "created_at"]},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={
                "base_manager_name": "prefetch_manager",
                "ordering": ["created_at"],
                "permissions": (("can_approve_posts", "Can approve posts"),),
            },
        ),
        migrations.AlterModelOptions(
            name="topic",
            options={"base_manager_name": "prefetch_manager", "ordering": ["created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="reaction",
            name="boards_reac_created_189025_brin",
        ),
        migrations.AlterField(
            model_name="historicalimage",
            name="title",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="image",
            name="title",
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
