# Generated by Django 4.2.1 on 2023-05-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boards", "0072_remove_additionaldata_unique_post_additional_data_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="additionaldata",
            name="data_type",
            field=models.CharField(
                choices=[("c", "chemdoodle"), ("f", "file"), ("m", "misc")], default="m", editable=False, max_length=1
            ),
        ),
    ]
