# Generated by Django 4.2.6 on 2023-10-06 21:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("boards", "0073_alter_additionaldata_data_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalboard",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalboard",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="historicalboardpreferences",
            name="background_image",
        ),
        migrations.RemoveField(
            model_name="historicalboardpreferences",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalimage",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalpost",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalpost",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="historicalpost",
            name="user",
        ),
        migrations.RemoveField(
            model_name="historicaltopic",
            name="history_user",
        ),
        migrations.DeleteModel(
            name="HistoricalAdditionalData",
        ),
        migrations.DeleteModel(
            name="HistoricalBoard",
        ),
        migrations.DeleteModel(
            name="HistoricalBoardPreferences",
        ),
        migrations.DeleteModel(
            name="HistoricalImage",
        ),
        migrations.DeleteModel(
            name="HistoricalPost",
        ),
        migrations.DeleteModel(
            name="HistoricalTopic",
        ),
    ]
