# Generated by Django 4.2.6 on 2023-10-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boards", "0074_remove_historicalboard_history_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="attribution",
            field=models.CharField(blank=True, default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="identity_hash",
            field=models.CharField(blank=True, default="", max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="session_key",
            field=models.CharField(blank=True, default="", max_length=40),
            preserve_default=False,
        ),
    ]
