# Generated by Django 4.2.7 on 2023-12-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boards", "0076_export"),
    ]

    operations = [
        migrations.AddField(
            model_name="export",
            name="post_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
