# Generated by Django 5.0 on 2023-12-05 14:50

import django.contrib.postgres.functions
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boards", "0077_export_post_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="additionaldata",
            name="created_at",
            field=models.DateTimeField(
                db_default=django.db.models.functions.datetime.Now(), editable=False
            ),
        ),
        migrations.AlterField(
            model_name="additionaldata",
            name="data_type",
            field=models.CharField(
                choices=[("c", "chemdoodle"), ("f", "file"), ("m", "misc")],
                db_default=models.Value("m"),
                editable=False,
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="additionaldata",
            name="id",
            field=models.UUIDField(
                db_default=django.contrib.postgres.functions.RandomUUID(),
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="board",
            name="created_at",
            field=models.DateTimeField(
                db_default=django.db.models.functions.datetime.Now(), editable=False
            ),
        ),
        migrations.AlterField(
            model_name="board",
            name="id",
            field=models.UUIDField(
                db_default=django.contrib.postgres.functions.RandomUUID(),
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="board",
            name="locked",
            field=models.BooleanField(db_default=models.Value(False)),
        ),
        migrations.AlterField(
            model_name="boardpreferences",
            name="allow_guest_replies",
            field=models.BooleanField(db_default=models.Value(False)),
        ),
        migrations.AlterField(
            model_name="boardpreferences",
            name="allow_image_uploads",
            field=models.BooleanField(db_default=models.Value(False)),
        ),
        migrations.AlterField(
            model_name="boardpreferences",
            name="allow_post_editing",
            field=models.BooleanField(db_default=models.Value(True)),
        ),
        migrations.AlterField(
            model_name="boardpreferences",
            name="background_color",
            field=models.CharField(db_default=models.Value("#ffffff"), max_length=7),
        ),
        migrations.AlterField(
            model_name="boardpreferences",
            name="background_opacity",
            field=models.FloatField(db_default=models.Value(1.0)),
        ),
        migrations.AlterField(
            model_name="boardpreferences",
            name="background_type",
            field=models.CharField(
                choices=[("c", "Color"), ("i", "Image")],
                db_default=models.Value("c"),
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="boardpreferences",
            name="board_type",
            field=models.CharField(
                choices=[("d", "Default"), ("r", "With Replies")],
                db_default=models.Value("d"),
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="boardpreferences",
            name="enable_chemdoodle",
            field=models.BooleanField(db_default=models.Value(False)),
        ),
        migrations.AlterField(
            model_name="boardpreferences",
            name="enable_identicons",
            field=models.BooleanField(db_default=models.Value(True)),
        ),
        migrations.AlterField(
            model_name="boardpreferences",
            name="enable_latex",
            field=models.BooleanField(db_default=models.Value(False)),
        ),
        migrations.AlterField(
            model_name="boardpreferences",
            name="id",
            field=models.UUIDField(
                db_default=django.contrib.postgres.functions.RandomUUID(),
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="boardpreferences",
            name="reaction_type",
            field=models.CharField(
                choices=[("n", "None"), ("l", "Like"), ("v", "Vote"), ("s", "Star")],
                db_default=models.Value("n"),
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="boardpreferences",
            name="require_post_approval",
            field=models.BooleanField(db_default=models.Value(False)),
        ),
        migrations.AlterField(
            model_name="boardpreferences",
            name="require_post_reapproval_on_edit",
            field=models.BooleanField(db_default=models.Value(False)),
        ),
        migrations.AlterField(
            model_name="export",
            name="created_at",
            field=models.DateTimeField(
                db_default=django.db.models.functions.datetime.Now(), editable=False
            ),
        ),
        migrations.AlterField(
            model_name="export",
            name="id",
            field=models.UUIDField(
                db_default=django.contrib.postgres.functions.RandomUUID(),
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="export",
            name="post_count",
            field=models.PositiveSmallIntegerField(db_default=models.Value(0)),
        ),
        migrations.AlterField(
            model_name="image",
            name="created_at",
            field=models.DateTimeField(
                db_default=django.db.models.functions.datetime.Now(), editable=False
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="id",
            field=models.UUIDField(
                db_default=django.contrib.postgres.functions.RandomUUID(),
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="image_type",
            field=models.CharField(
                choices=[("b", "Background"), ("p", "Post")],
                db_default=models.Value("b"),
                help_text="Image type",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="allow_replies",
            field=models.BooleanField(db_default=models.Value(True)),
        ),
        migrations.AlterField(
            model_name="post",
            name="approved",
            field=models.BooleanField(db_default=models.Value(True)),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                db_default=django.db.models.functions.datetime.Now(), editable=False
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.UUIDField(
                db_default=django.contrib.postgres.functions.RandomUUID(),
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="reaction",
            name="created_at",
            field=models.DateTimeField(
                db_default=django.db.models.functions.datetime.Now(), editable=False
            ),
        ),
        migrations.AlterField(
            model_name="reaction",
            name="id",
            field=models.UUIDField(
                db_default=django.contrib.postgres.functions.RandomUUID(),
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="reaction",
            name="reaction_score",
            field=models.IntegerField(db_default=models.Value(1)),
        ),
        migrations.AlterField(
            model_name="reaction",
            name="reaction_type",
            field=models.CharField(
                choices=[("n", "None"), ("l", "Like"), ("v", "Vote"), ("s", "Star")],
                db_default=models.Value("l"),
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="created_at",
            field=models.DateTimeField(
                db_default=django.db.models.functions.datetime.Now(), editable=False
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="id",
            field=models.UUIDField(
                db_default=django.contrib.postgres.functions.RandomUUID(),
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="locked",
            field=models.BooleanField(db_default=models.Value(False)),
        ),
    ]
