name: 'Combine PRs'

on:
  workflow_dispatch:
    inputs:
      branchPrefix:
        description: 'Branch prefix to find combinable PRs based on'
        required: true
        default: 'dependabot'
      mustBeGreen:
        description: 'Only combine PRs that are green (status is success)'
        required: true
        default: true
      combineBranchName:
        description: 'Name of the branch to combine PRs into'
        required: true
        default: 'combined-prs'
      ignoreLabel:
        description: 'Exclude PRs with this label'
        required: true
        default: 'nocombine'

jobs:
  combine-prs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: maadhattah/combine-dependabot-prs@main
        with:
          branchPrefix: ${{ github.event.inputs.branchPrefix }}
          mustBeGreen: ${{ github.event.inputs.mustBeGreen }}
          combineBranchName: ${{ github.event.inputs.combineBranchName }}
          ignoreLabel: ${{ github.event.inputs.ignoreLabel }}
          baseBranch: "main"
          openPR: true
          allowSkipped: false
